package HibernateServerFiles2;

// Generated Jun 2, 2015 8:02:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "usersonline")
public class Message implements java.io.Serializable {

	private Integer id;
	private User user;
	private String message;
	private Set<Replies> replieses = new HashSet<Replies>(0);

	public Message() {
	}

	public Message(User user, String message) {
		this.user = user;
		this.message = message;
	}

	public Message(User user, String message, Set<Replies> replieses) {
		this.user = user;
		this.message = message;
		this.replieses = replieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "message", nullable = false, length = 140)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	public Set<Replies> getReplieses() {
		return this.replieses;
	}

	public void setReplieses(Set<Replies> replieses) {
		this.replieses = replieses;
	}

}
