package HibernateServerFiles2;

// Generated Jun 2, 2015 8:02:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Relationship generated by hbm2java
 */
@Entity
@Table(name = "relationship", catalog = "usersonline")
public class Relationship implements java.io.Serializable {

	private Integer id;
	private User userByFollower;
	private User userByFollowee;

	public Relationship() {
	}

	public Relationship(User userByFollower, User userByFollowee) {
		this.userByFollower = userByFollower;
		this.userByFollowee = userByFollowee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "follower", nullable = false)
	public User getUserByFollower() {
		return this.userByFollower;
	}

	public void setUserByFollower(User userByFollower) {
		this.userByFollower = userByFollower;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "followee", nullable = false)
	public User getUserByFollowee() {
		return this.userByFollowee;
	}

	public void setUserByFollowee(User userByFollowee) {
		this.userByFollowee = userByFollowee;
	}

}
