package HibernateServerFiles2;

// Generated Jun 2, 2015 8:02:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Replies generated by hbm2java
 */
@Entity
@Table(name = "replies", catalog = "usersonline")
public class Replies implements java.io.Serializable {

	private Integer idreplies;
	private Message message;
	private User user;
	private String reply;

	public Replies() {
	}

	public Replies(Message message, User user, String reply) {
		this.message = message;
		this.user = user;
		this.reply = reply;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idreplies", unique = true, nullable = false)
	public Integer getIdreplies() {
		return this.idreplies;
	}

	public void setIdreplies(Integer idreplies) {
		this.idreplies = idreplies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentuser")
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "reply", length = 45)
	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

}
